spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.4.207:3306/dbgirl?characterEncoding=UTF-8&useUnicode=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: dalong
    password: rotrot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect